/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ico.aragon;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Maine extends javax.swing.JFrame {

    /**
     * Creates new form Maine
     */
    public Maine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJ1 = new javax.swing.JButton();
        btnJ2 = new javax.swing.JButton();
        punJ1 = new javax.swing.JLabel();
        punJ2 = new javax.swing.JLabel();
        Deuce = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marcador de Tennis");

        btnJ1.setText("Jugador 1 Anota");
        btnJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ1ActionPerformed(evt);
            }
        });

        btnJ2.setText("Jugador 2 Anota");
        btnJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ2ActionPerformed(evt);
            }
        });

        punJ1.setFont(new java.awt.Font("Tahoma", 1, 69)); // NOI18N
        punJ1.setText("0");

        punJ2.setFont(new java.awt.Font("Tahoma", 1, 69)); // NOI18N
        punJ2.setText("0");

        Deuce.setFont(new java.awt.Font("Tahoma", 0, 69)); // NOI18N
        Deuce.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Deuce)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(punJ1)
                                .addGap(98, 98, 98)
                                .addComponent(punJ2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Deuce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(punJ1)
                    .addComponent(punJ2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ1ActionPerformed
        // TODO add your handling code here:
        switch (punJ1.getText()){
            case "0":
                punJ1.setText("15");
                break;
            case "15":
                punJ1.setText("30");
                break;
            case "30":
                if(punJ2.getText() != "40"){
                    punJ1.setText("40");
                    break;
                }
                else{
                    punJ1.setText("");
                    punJ2.setText("");
                    Deuce.setText("Deuce");
                    break;
                }
            case "40":
            if(punJ2.getText() != "A"){
                JOptionPane.showMessageDialog(rootPane, "A Winner Is You, P1");
                punJ2.setText("0");
                punJ1.setText("0");
                break;
            }
            else{
                punJ1.setText("");
                punJ2.setText("");
                Deuce.setText("Deuce");
                break;
            }
            case "":
                punJ1.setText("A");
                punJ2.setText("40");
                Deuce.setText("");
                break;
            case "A":
                JOptionPane.showMessageDialog(rootPane, "A Winner Is You, P1");
                punJ2.setText("0");
                punJ1.setText("0");
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "Rompiste mi programa :'v");
                punJ2.setText("0");
                punJ1.setText("0");
                break;
        }

    }//GEN-LAST:event_btnJ1ActionPerformed

    private void btnJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ2ActionPerformed
        // TODO add your handling code here:
        switch (punJ2.getText()){
        case "0":
            punJ2.setText("15");
            break;
        case "15":
            punJ2.setText("30");
            break;
        case "40":
            if(punJ1.getText() != "A"){
                JOptionPane.showMessageDialog(rootPane, "A Winner Is You, P2");
                punJ2.setText("0");
                punJ1.setText("0");
                break;
            }
            else{
                punJ1.setText("");
                punJ2.setText("");
                Deuce.setText("Deuce");
                break;
            }
        case "30":
            if(punJ1.getText() != "40"){
                    punJ2.setText("40");
                    break;
                }
            else{
                    punJ1.setText("");
                    punJ2.setText("");
                    Deuce.setText("Deuce");
                    break;
                }
        case "A":
                JOptionPane.showMessageDialog(rootPane, "A Winner Is You, P2");
                punJ2.setText("0");
                punJ1.setText("0");
                break;
        case "":
            punJ2.setText("A");
            punJ1.setText("40");
            Deuce.setText("");
            break;
        default:
            JOptionPane.showMessageDialog(rootPane, "Rompiste mi programa :'v");
            punJ2.setText("0");
            punJ1.setText("0");
            break;
        }
    }//GEN-LAST:event_btnJ2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Deuce;
    private javax.swing.JButton btnJ1;
    private javax.swing.JButton btnJ2;
    private javax.swing.JLabel punJ1;
    private javax.swing.JLabel punJ2;
    // End of variables declaration//GEN-END:variables
}
